<?xml version="1.0"?>
<package format="3">
  <name>multi_sensor_alignment</name>
  <version>0.0.0</version>
  <description>Aligns multiple sensors to each other and the robotic platform</description>

  <maintainer email="charles.c.ellison@erdc.dren.mil">Chuck Ellison</maintainer>
  <maintainer email="steven.bunkley@erdc.dren.mil">Steven Bunkley</maintainer>

  <!-- One license tag required, multiple allowed, one license per tag -->
  <!-- Commonly used license strings: -->
  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>cv_bridge</depend>

</package>
